require 'uri'
require 'base64'
require 'openssl'
require 'faraday'
require 'json'
require 'faraday_middleware'
require 'dotenv/load'

require_relative './errors'
require_relative './rest/v1'
require_relative './rest/v2'
require_relative './ws/ws2'
