require 'uri'
require 'faraday'
require 'faraday_middleware'
require 'bitfinex/configurable'
require 'bitfinex/base_resource'
require 'bitfinex/errors'
require 'bitfinex/connection'
require 'bitfinex/ticker'
require 'bitfinex/trades'
require 'bitfinex/funding_book'
require 'bitfinex/orderbook'
require 'bitfinex/lends'
require 'bitfinex/symbols'
require 'bitfinex/stats'
require 'bitfinex/client'

